# 第十章 错误处理与异常



## 10.1 关于错误处理



## 10.2 异常处理

> 文件名: 行号:in 方法名: 错误信息（异常类名）
>
> from 文件名: 行号:in 方法名



## 10.3 异常处理的写法

```
begin
　可能会发生异常的处理
rescue => 把异常对象赋值给变量
　发生异常时的处理
end
```

### 常用方法

`e.class`，异常的种类

`e.message`，异常信息，观察发现效果同 `e`

`e.backtrace`，异常发生的位置信息（`$@` 与 `$!.backtrace` 是等价的）

```
class A
  def self.foo
    begin
      nil.count
    rescue => e
      puts "e: #{e}"
      puts "e.class: #{e.class}"
      puts "e.message: #{e.message}"
      puts "e.backtrace: #{e.backtrace}"
    end
  end
end

A.foo
```



## 10.4 后处理

不管是否发生异常都希望执行的处理，用 `ensure`

```
class B
  def self.foo
    begin
      nil.count
    rescue => e
      puts "#{e.class}: #{e}"
    ensure
      puts "I'm relly good !"
    end
  end
end

B.foo
```



## 10.5 重试

 `rescue` 中使用 `retry` 后，`begin` 下的处理会再重做一遍

```
class C
  def self.foo
    i = 0
    begin
      nil.count
    rescue => e
      i += 1
      puts i
      retry if i<3
      puts "#{e.class}: #{e}"
    end
  end
end

C.foo  #=>
1
2
3
NoMethodError: undefined method `count' for nil:NilClass
```



## 10.6 rescue 修饰符

```
String() rescue 0   #=> 0
String(2) rescue 0  #=> "2"
```



## 10.7 异常处理语法的补充

整个方法内的程序都用 `begin ～ end` 包含的话，我们就可以省略 `begin` 以及 `end`

一般我们不会在类定义中使用 rescue 捕获异常

```
class B
  def self.foo
    nil.count
  rescue => e
    puts "#{e.class}: #{e}"
  ensure
    puts "I'm relly good !"
  end
end

B.foo
```



## 10.8 指定需要捕捉的异常

可以指定多个 `rescue`

```
class D
  def self.foo(val)
    case val
    when 1
      File.open(bar)
    when 2
      File.open()
    else
      nil.bar
    end
  rescue NameError => e
    puts "#{e.class}: #{e}"
  rescue ArgumentError => e
    puts "#{e.class}: #{e}"
  rescue NoMethodError => e
    puts "#{e.class}: #{e}"
  end
end

D.foo(1)  		#=> NameError: undefined local variable or method `bar' for D:Class
D.foo(2)			#=> ArgumentError: wrong number of arguments (given 0, expected 1..3)
D.foo(3)      #=> NoMethodError: undefined method `bar' for nil:NilClass
D.foo("abc")  #=> NoMethodError: undefined method `bar' for nil:NilClass
```



## 10.9 异常类

`ancestors` 方法，查看常用类的祖先。发现最常用的都是 `StandardError` 类。当 `rescue` 中不指定异常类时，程序会默认捕捉 `StandardError` 类

```
NameError.ancestors  #=> [DidYouMean::Correctable, NameError, StandardError, Exception, Object, Kernel, BasicObject]

ArgumentError.ancestors  #=> [ArgumentError, StandardError, Exception, Object, Kernel, BasicObject]

NoMethodError.ancestors  #=> [NoMethodError, DidYouMean::Correctable, NameError, StandardError, Exception, Object, Kernel, BasicObject]
```

### 自定义异常类

一般会先定义继承 `StandardError` 类的新类，然后再继承这个新类

```
MyError = Class.new(StandardError)
MyError1 = Class.new(MyError)
MyError2 = Class.new(MyError)

MyError.ancestors   #=> [MyError, StandardError, Exception, Object, Kernel, BasicObject]
MyError1.ancestors  #=> [MyError1, MyError, StandardError, Exception, Object, Kernel, BasicObject]
```

上面的写法与下面等价

```
class MyError < StandardError
end
```



## 10.10 主动抛出异常

使用 `raise` 方法，可以使程序主动抛出异常

* raise message
* **raise 异常类**
* **raise 异常类，message**
* **raise**，在 `rescue` 中调用时，会再次抛出最后一次发生的异常

